name: sixplace
description: A mobile-first, responsive application foundation for Flutter.
version: 0.0.1

homepage: https://github.com/innovatenestlabs-inl/sixplace
repository: https://github.com/innovatenestlabs-inl/sixplace
issue_tracker: https://github.com/innovatenestlabs-inl/sixplace/issues

environment:
  sdk: ">=3.9.0 <4.0.0"
  flutter: ">=3.35.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter: